Milestone 5: Private-events
Ceejayski/Private-events pull request #1
Opened 2020-12-08 13:24 UTC by enaburekhan

**Private events built with Ruby on rails.**
**In this project:**

- Create associations between User, Event and Attendance
- Create logic in view to separate upcoming events from past events
- Create sessions to cache user_id on the browser
- Use bootstrap for styling

2020-12-08 17:04 UTC, voscarmv requested changes
# Nice work so far, team. 👍 

## However, there are some changes required 👀 🧰 🔨 🔧 

- Please add validation to the event name so that it's not possible to create events with an empty name.
- Please add validation to the event date so that it's required for the event to have a date. (the date can not be left empty)
- Currently there is no way to attend events in the app. Please add a button or some sort of input where a user can attend an event.
- Please make sure the Event belongs to User and has a foreign key with `has_many :events, foreign_key: :creator_id`
- Please read my code comments for further necessary changes.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-12-08 17:04 UTC, voscarmv commented on app/controllers/events_controller.rb
> +    @upcoming_events = Event.upcoming.paginate(page: params[:page], per_page: 2).order(created_at: :desc)
Please move the `paginate` and `order` preprocessing to the scope methods instead of writing them here.

2020-12-09 14:25 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Eric Enaburekhan & Ceejay Okoli** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to correct before you can go ahead:

- [ ] User's should be able to attend an event
- [ ] Remove commented code in User class
- [ ] Remove commented code in Attendance
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2020-12-09 21:07 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__Your commitment and genuinely in this project is commendable. 
You just have some changes to make before this project can be approved.__

**[ REQUIRED CHANGES ]**

- [ ] There should be NO application logic in the views nor helpers (no `Post.new, Comment.create, current_user.friends.find_by(...)...`). Everything connected with data processing should be encapsulated in models and used in controllers.
- Check my inline comments for details.

- [ ] The event's show page displays the list of attendants 
- Right now, the event show page only displays a number of attendants. Since the requirement wants you to display the list of attendants, kindly refactor your code to welcome this development.

- [ ] You still have some commented code in user.rb and attendance.rb


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2020-12-09 21:07 UTC, teekaytech commented on app/views/layouts/_nav.html.erb
> +      <%end%>
This logic can and should be separated into a helper file.

2020-12-09 21:07 UTC, teekaytech commented on app/views/users/index.html.erb
> +                  <% attendance = Attendance.find_by(event_id: params[:event_id], user_id: user.id) %>
`Attendance.find_by` query should have been done in the users_controller#index action.

2020-12-09 21:07 UTC, teekaytech commented on app/views/users/show.html.erb
> +              <% if @user.events.empty? %>
@user.events query should be made in the users_controller#show action.

2020-12-09 21:07 UTC, teekaytech commented on app/views/users/show.html.erb
> +              <% if @user.attended_events.where('date >= ?', Date.today).count.zero? %>
@user.attended_events should also be called in the controller.

2020-12-10 11:49 UTC, enaburekhan commented
**Code review changes effected:**

- The event_show view shows the list of attendees as shown in the image below:

![attendee](https://user-images.githubusercontent.com/51296741/101768349-bf84b800-3ae5-11eb-801e-3537e943e281.png)

- refactor codes with logic in view to helper.

2020-12-10 14:34 UTC, Dandush03 approved these changes
# Status :rocket: Approved :rocket: 
### Great Work Guys!
# Happy Coding :+1:

2020-12-10 14:56 UTC, merged